### PR TITLE
Update YOLOv5 notebook

### PR DESCRIPTION
**Pull request by danielmaxsiegel**

### CODE REVIEW

**Comment by michaeldavidmcallister** [comment]
Approved

**Review by eduardomoraes — APPROVED** [review]
Lgtm

**Comment by danielmaxsiegel** [comment]
Thanks @michaeldavidmcallister !

**Comment by michaeldavidmcallister** [comment]
Hom's contribution

**Comment by danielmaxsiegel** [comment]
And @eduardomoraes

**Pull request merged**
